### ISSUE TITLE
leetcode 322. Coin Change (Python) — 杰弗里 · 时光博客(Jeffrey's Blog)

### ISSUE THREAD

**Issue by zhenyu0519** [zhenyu0519/zhenyu0519.github.io#34]
https://zhenyu0519.github.io/2020/02/27/lc322/ 

 Leetcode 322. Coin Change (Python)

**Comment by roshandec29** [comment]
There is a change in the code.

Please make it dp = [amount+1 for _ in range(amount+1)] to get it accepted in leetcode.
